export enum ProductoTipo {
  RETAIL = 'RETAIL',
  RETAIL_INGREDIENTE = 'RETAIL_INGREDIENTE',
  ELABORADO_SIN_VARIACION = 'ELABORADO_SIN_VARIACION',
  ELABORADO_CON_VARIACION = 'ELABORADO_CON_VARIACION',
  COMBO = 'COMBO',
} 